---
name: autogenerate-conferences

on:
  push:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkoput code
        uses: actions/checkout@v4

      - name: run merge script
        run: bash ${PWD}/merge.sh

      - name: Pushes to hci-deadlines-hhn
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'conferences.yml'
          destination_branch: 'gh-pages'
          destination_repo: 'hci-deadlines-hhn/hci-deadlines-hhn.github.io'
          destination_folder: '_data'
          user_email: 'afi.89@outlook.com'
          user_name: 'hci-deadlines-hhn'
          commit_message: 'Updated conferences'
